handling integration test

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -33,7 +33,15 @@ jobs:
       - name: Test
         run: |
           cd src
-          dotnet test --no-restore --verbosity normal --logger:trx --collect:"XPlat Code Coverage" --results-directory ./TestResults    
+          dotnet test --no-restore --verbosity normal --logger:trx --collect:"XPlat Code Coverage" --results-directory ./TestResults
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: DotNet Tests          # Name of the check run which will be created
+          path: |
+            **/*.trx
+          reporter: dotnet-trx        # Format of test results
       - name: Integration Test
         env:
             ppuser: '${{ secrets.POWER_PLATFORM_USER }}'
@@ -46,14 +54,6 @@ jobs:
           playwright install            
           dotnet run -- -e "ceb95cca-da1d-ed58-8af8-117cb4081f16" -t "f2c52b3d-d88e-4892-9785-d5b7c7016725" -i "../../samples/buttonclicker/testPlan.fx.yaml" -o "../../testResult"
           dotnet run -- -e "ceb95cca-da1d-ed58-8af8-117cb4081f16" -t "f2c52b3d-d88e-4892-9785-d5b7c7016725" -i "../../samples/nestedgallery/testPlan.fx.yaml" -o "../../testResult"   
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: DotNet Tests          # Name of the check run which will be created
-          path: |
-            **/*.trx
-          reporter: dotnet-trx        # Format of test results
       - name: Copy Coverage report
         run: cp src/TestResults/**/coverage.cobertura.xml coverage.cobertura.xml
       - name: Code coverage report
@@ -70,4 +70,4 @@ jobs:
         if: github.event_name == 'pull_request'
         with:
           recreate: true
-          path: code-coverage-results.md    
+          path: code-coverage-results.md
